-- schema.sql
-- Drop and recreate the public schema (purges the database)
-- Then creates enum types and core tables translated from prisma/schema.prisma.
-- NOTE: This is a faithful manual translation for convenience. For a canonical
-- SQL DDL generated by Prisma, run `npx prisma migrate dev` or use
-- `npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script`.

-- Purge the DB: drops everything in public
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- Useful extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enums (translated from Prisma)
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invite_status') THEN
        CREATE TYPE invite_status AS ENUM ('PENDING','ACCEPTED','EXPIRED','REVOKED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_audit_event_type') THEN
        CREATE TYPE org_audit_event_type AS ENUM (
            'INVITE_SENT','INVITE_RESENT','INVITE_REVOKED','INVITE_ACCEPTED',
            'ROLE_CHANGED','MEMBER_DEACTIVATED','MEMBER_REACTIVATED','ORG_UPDATED'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role') THEN
        CREATE TYPE role AS ENUM ('ADMIN','MANAGER','EMPLOYEE');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
        CREATE TYPE task_status AS ENUM (
            'PENDING','ASSIGNED','SEARCHING','REASSIGNED','FOUND','SAMPLE_COLLECTED',
            'AWAITING_APPROVAL','PURCHASED','BRANDING_IN_PROGRESS','BRANDING_COMPLETE','DISTRIBUTED','UNAVAILABLE'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vendor_type') THEN
        CREATE TYPE vendor_type AS ENUM ('SOURCING','BRANDING','BOTH');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_priority') THEN
        CREATE TYPE task_priority AS ENUM ('LOW','NORMAL','HIGH','URGENT');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'photo_kind') THEN
        CREATE TYPE photo_kind AS ENUM ('SAMPLE','ARTWORK','BRANDED_PROOF','DELIVERY_PROOF');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_event_type') THEN
        CREATE TYPE task_event_type AS ENUM (
            'CREATED','ASSIGNED','REASSIGNED','STATUS_CHANGED','PHOTO_ADDED','VENDOR_LINKED',
            'BRANDING_VENDOR_LINKED','ARTWORK_UPLOADED','DISTRIBUTION_RECORDED','COMMENT_ADDED'
        );
    END IF;
END$$;

-- Core tables (selected, translated). Add or extend as needed.

CREATE TABLE organizations (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  logoUrl TEXT,
  contactEmail TEXT,
  contactPhone TEXT,
  currency TEXT NOT NULL DEFAULT 'KES',
  plan TEXT NOT NULL DEFAULT 'FREE',
  createdAt timestamptz NOT NULL DEFAULT now(),
  updatedAt timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  emailVerified timestamptz,
  image TEXT,
  phone TEXT,
  role role NOT NULL DEFAULT 'EMPLOYEE',
  active boolean NOT NULL DEFAULT true,
  createdAt timestamptz NOT NULL DEFAULT now(),
  organizationId TEXT,
  CONSTRAINT fk_users_organization FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE SET NULL
);
CREATE INDEX idx_users_organization ON users(organizationId);

CREATE TABLE accounts (
  id TEXT PRIMARY KEY,
  userId TEXT NOT NULL,
  type TEXT NOT NULL,
  provider TEXT NOT NULL,
  providerAccountId TEXT NOT NULL,
  refresh_token TEXT,
  access_token TEXT,
  expires_at integer,
  token_type TEXT,
  scope TEXT,
  id_token TEXT,
  session_state TEXT,
  CONSTRAINT accounts_user_fk FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uidx_accounts_provider_account ON accounts(provider, providerAccountId);

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  sessionToken TEXT UNIQUE NOT NULL,
  userId TEXT NOT NULL,
  expires timestamptz NOT NULL,
  CONSTRAINT sessions_user_fk FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE verification_tokens (
  identifier TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires timestamptz NOT NULL,
  PRIMARY KEY(identifier, token)
);

CREATE TABLE invites (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  role role NOT NULL DEFAULT 'EMPLOYEE',
  token TEXT UNIQUE NOT NULL,
  status invite_status NOT NULL DEFAULT 'PENDING',
  expiresAt timestamptz NOT NULL,
  acceptedAt timestamptz,
  createdAt timestamptz NOT NULL DEFAULT now(),
  updatedAt timestamptz NOT NULL DEFAULT now(),
  organizationId TEXT NOT NULL,
  invitedById TEXT NOT NULL,
  CONSTRAINT invites_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT invites_inviter_fk FOREIGN KEY (invitedById) REFERENCES users(id)
);
CREATE INDEX idx_invites_organization ON invites(organizationId);
CREATE INDEX idx_invites_email ON invites(email);

CREATE TABLE org_audit_logs (
  id TEXT PRIMARY KEY,
  organizationId TEXT NOT NULL,
  actorId TEXT,
  type org_audit_event_type NOT NULL,
  targetEmail TEXT,
  fromValue TEXT,
  toValue TEXT,
  note TEXT,
  createdAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT org_audit_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE INDEX idx_org_audit_org ON org_audit_logs(organizationId);

CREATE TABLE materials (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL,
  description TEXT,
  stockOnHand double precision NOT NULL DEFAULT 0,
  reorderThreshold double precision NOT NULL DEFAULT 0,
  createdAt timestamptz NOT NULL DEFAULT now(),
  updatedAt timestamptz NOT NULL DEFAULT now(),
  organizationId TEXT NOT NULL,
  CONSTRAINT materials_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE INDEX idx_materials_category ON materials(category);
CREATE INDEX idx_materials_org ON materials(organizationId);

CREATE TABLE material_photos (
  id TEXT PRIMARY KEY,
  materialId TEXT NOT NULL,
  url TEXT NOT NULL,
  caption TEXT,
  createdAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT material_photos_material_fk FOREIGN KEY (materialId) REFERENCES materials(id) ON DELETE CASCADE
);

CREATE TABLE vendors (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type vendor_type NOT NULL DEFAULT 'SOURCING',
  address TEXT,
  contactName TEXT,
  phone TEXT,
  email TEXT,
  notes TEXT,
  rating integer,
  createdAt timestamptz NOT NULL DEFAULT now(),
  updatedAt timestamptz NOT NULL DEFAULT now(),
  organizationId TEXT NOT NULL,
  CONSTRAINT vendors_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE INDEX idx_vendors_org ON vendors(organizationId);

CREATE TABLE vendor_materials (
  id TEXT PRIMARY KEY,
  vendorId TEXT NOT NULL,
  materialId TEXT NOT NULL,
  price double precision NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  quantityAvail double precision,
  lastCheckedAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vm_vendor_fk FOREIGN KEY (vendorId) REFERENCES vendors(id) ON DELETE CASCADE,
  CONSTRAINT vm_material_fk FOREIGN KEY (materialId) REFERENCES materials(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX uidx_vendor_material ON vendor_materials(vendorId, materialId);

CREATE TABLE projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  clientName TEXT,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  createdAt timestamptz NOT NULL DEFAULT now(),
  organizationId TEXT NOT NULL,
  CONSTRAINT projects_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE INDEX idx_projects_org ON projects(organizationId);

CREATE TABLE sourcing_tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  materialId TEXT NOT NULL,
  quantityNeeded double precision NOT NULL,
  status task_status NOT NULL DEFAULT 'PENDING',
  priority task_priority NOT NULL DEFAULT 'NORMAL',
  projectId TEXT,
  vendorId TEXT,
  quotedPrice double precision,
  brandingVendorId TEXT,
  brandingMethod TEXT,
  brandingCost double precision,
  artworkUrl TEXT,
  assignedToId TEXT,
  createdById TEXT NOT NULL,
  lastActivityAt timestamptz NOT NULL DEFAULT now(),
  createdAt timestamptz NOT NULL DEFAULT now(),
  updatedAt timestamptz NOT NULL DEFAULT now(),
  organizationId TEXT NOT NULL,
  CONSTRAINT st_material_fk FOREIGN KEY (materialId) REFERENCES materials(id),
  CONSTRAINT st_project_fk FOREIGN KEY (projectId) REFERENCES projects(id),
  CONSTRAINT st_vendor_fk FOREIGN KEY (vendorId) REFERENCES vendors(id),
  CONSTRAINT st_branding_vendor_fk FOREIGN KEY (brandingVendorId) REFERENCES vendors(id),
  CONSTRAINT st_assigned_fk FOREIGN KEY (assignedToId) REFERENCES users(id),
  CONSTRAINT st_createdby_fk FOREIGN KEY (createdById) REFERENCES users(id),
  CONSTRAINT st_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE INDEX idx_sourcing_tasks_status ON sourcing_tasks(status);
CREATE INDEX idx_sourcing_tasks_assigned ON sourcing_tasks(assignedToId);
CREATE INDEX idx_sourcing_tasks_org ON sourcing_tasks(organizationId);

CREATE TABLE task_photos (
  id TEXT PRIMARY KEY,
  taskId TEXT NOT NULL,
  url TEXT NOT NULL,
  kind photo_kind NOT NULL DEFAULT 'SAMPLE',
  caption TEXT,
  createdAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT task_photos_task_fk FOREIGN KEY (taskId) REFERENCES sourcing_tasks(id) ON DELETE CASCADE
);

CREATE TABLE task_events (
  id TEXT PRIMARY KEY,
  taskId TEXT NOT NULL,
  actorId TEXT NOT NULL,
  type task_event_type NOT NULL,
  fromValue TEXT,
  toValue TEXT,
  note TEXT,
  createdAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT task_events_task_fk FOREIGN KEY (taskId) REFERENCES sourcing_tasks(id) ON DELETE CASCADE,
  CONSTRAINT task_events_actor_fk FOREIGN KEY (actorId) REFERENCES users(id)
);
CREATE INDEX idx_task_events_task ON task_events(taskId);

CREATE TABLE task_comments (
  id TEXT PRIMARY KEY,
  taskId TEXT NOT NULL,
  authorId TEXT NOT NULL,
  body TEXT NOT NULL,
  createdAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT task_comments_task_fk FOREIGN KEY (taskId) REFERENCES sourcing_tasks(id) ON DELETE CASCADE,
  CONSTRAINT task_comments_author_fk FOREIGN KEY (authorId) REFERENCES users(id)
);

CREATE TABLE distribution_records (
  id TEXT PRIMARY KEY,
  taskId TEXT NOT NULL,
  organizationId TEXT NOT NULL,
  recipientName TEXT NOT NULL,
  recipientContact TEXT,
  quantity double precision NOT NULL,
  deliveryDate timestamptz NOT NULL DEFAULT now(),
  deliveredById TEXT NOT NULL,
  proofPhotoUrl TEXT,
  notes TEXT,
  createdAt timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dist_task_fk FOREIGN KEY (taskId) REFERENCES sourcing_tasks(id) ON DELETE CASCADE,
  CONSTRAINT dist_delivered_by_fk FOREIGN KEY (deliveredById) REFERENCES users(id),
  CONSTRAINT dist_org_fk FOREIGN KEY (organizationId) REFERENCES organizations(id)
);
CREATE INDEX idx_distribution_task ON distribution_records(taskId);
CREATE INDEX idx_distribution_org ON distribution_records(organizationId);

-- Leads table: mapped to existing public-site table `leads`. Uses UUID id.
CREATE TABLE leads (
  id uuid PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  organization_id TEXT NOT NULL,
  brand TEXT NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  service TEXT,
  preferred_date date,
  location TEXT,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'new',
  converted_task_id TEXT,
  CONSTRAINT leads_org_fk FOREIGN KEY (organization_id) REFERENCES organizations(id)
);
CREATE INDEX idx_leads_org ON leads(organization_id);
CREATE INDEX idx_leads_status ON leads(status);

-- End of translated DDL. You can extend this file with additional constraints,
-- triggers, or materialized views as needed. For an authoritative DDL that exactly
-- matches Prisma's migration output, prefer generating via Prisma Migrate.
